// <auto-generated />
using System;
using CIS2055___Nemesys.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CIS2055___Nemesys.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220509122953_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CIS2055___Nemesys.Models.Documents.Report", b =>
                {
                    b.Property<int>("RRN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateAndTimeOfReport")
                        .HasColumnType("datetime2");

                    b.Property<string>("Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reporter_Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("upvotes")
                        .HasColumnType("int");

                    b.HasKey("RRN");

                    b.ToTable("Reports");

                    b.HasData(
                        new
                        {
                            RRN = 1,
                            DateAndTimeOfReport = new DateTime(2022, 5, 9, 14, 29, 53, 214, DateTimeKind.Local).AddTicks(8518),
                            Desc = "desctiption: hazardous",
                            Location = "Malta",
                            Reporter_Email = "email@mail.com",
                            Title = "Disaster1",
                            upvotes = 0
                        },
                        new
                        {
                            RRN = 2,
                            DateAndTimeOfReport = new DateTime(2022, 5, 9, 14, 29, 53, 219, DateTimeKind.Local).AddTicks(7426),
                            Desc = "desctiption: hazardous",
                            Location = "Malta",
                            Reporter_Email = "email@mail.com",
                            Title = "Disaster2",
                            upvotes = 0
                        },
                        new
                        {
                            RRN = 3,
                            DateAndTimeOfReport = new DateTime(2022, 5, 9, 14, 29, 53, 219, DateTimeKind.Local).AddTicks(7483),
                            Desc = "desctiption: hazardous",
                            Location = "Malta",
                            Reporter_Email = "email@mail.com",
                            Title = "Disaster3",
                            upvotes = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
